export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CURRENT_USER = 'CURRENT_USER';

export const LOADING_STUDENTS = 'LOADING_STUDENTS';
export const LOADING_STUDENT = 'LOADING_STUDENT';
export const OBTAIN_STUDENTS = 'OBTAIN_STUDENTS';
export const OBTAIN_STUDENT = 'OBTAIN_STUDENT';
export const SAVE_STUDENT = 'SAVE_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';